---
label: Services
hide_body: false
is_partial: false
fields:
- name: why
  label: Why
  type: list
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: min-price
  label: Min price
  type: text
  hidden: false
  default: ''
- type: text
  name: title
  label: Title
  description: The title of the page. May be visible.
- type: tag_list
  name: tags_for_the_page
  label: Tags for the page
  description: Add tags that pertain to this page
- type: field_group_list
  name: pricepackage
  label: PricePackage
  description: Enter the prices for each type of package for the services you provide
  fields:
  - type: text
    name: Package_Name
    label: PackageName
    description: Enter the name of the package(gold, platinum etc)
    config:
      required: true
  - type: list
    name: availablefeatures
    label: AvailableFeatures
    description: Features available under this package
  - type: number
    name: price
    label: PackagePrice
    description: Enter the price for this package
    config:
      min: '1'
      max: '100000000'
      required: true
- type: select
  config:
    source:
      type: pages
      section: services
  label: category
  name: category
  description: What category does this service fall into?
- type: textarea
  name: description
  label: Description
  description: make it keyword rich. WIll be used by jekyll-seo
- type: textarea
  name: sub-title
  label: Sub-Title
  description: small description. Might be visible
- type: text
  name: cta
  label: CTA
  description: the text that appears on the call-to-action button
- type: text
  name: bg-color
  label: bg-color
  description: Background Color
- type: text
  name: fg-color
  label: fg-color
  description: The text color. Make it high contrast with respect to the background.
- type: text
  name: layout
  label: Layout
  description: The layout of the page.Default if not mentioned.
  default: service
- type: file
  name: backgroundimage
  label: BackgroundImage
  description: Choose a background img for the service
pages:
- _services/digital-marketing.md
- _services/branding.md
- _services/web-development.html
- _services/seo.md
