---
hide_body: false
is_partial: false
fields:
- name: why
  label: Why
  type: list
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
